---
# Secure mysql installation - mysql_secure_installation script analogue

- name: remove test database
  command: mysql -e "DROP DATABASE IF EXISTS test;"

- name: deny remote root access
  command: mysql -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"

- name: deny anonymous access
  command: mysql -e "DELETE FROM mysql.user WHERE User='';"

- name: flush privileges
  command: mysql -e "FLUSH PRIVILEGES;"

